### ISSUE TITLE
Z80 Errata

### ISSUE THREAD

**Issue by floooh** [floooh/v6502r#2]
Current theory: the netlist is probably from a Zilog Z8400, not an original Z80.

Triggering an IM1 interrupt during a JR instruction jumps to 0x30, not 0x38:
```
	ei
	im 1
l0:	jr l0	; triggering INT in this loop...

	org 30h
l1:	jr l1	; ...jumps here

	org 38h
l2:	jr l2	; ...but should jump here
```

WZH should be set to 0x33 (value of A), but is set to zero at end of LD (nn),A:
```
	ld a,33h
	ld (1111h),a
```

Same here: WZH should be 0x33, but is zero.
```
	ld a,33h
	ld bc,1111h
	ld (bc),a
```

Note that the differing WZH behaviour could be an indication that the netlist is actually from a Russian (or East German?) Z80 clone, see [memptr_eng.txt](https://github.com/floooh/emu-info/blob/master/z80/memptr_eng.txt).

The undocumented XF and YF flags are cleared in BIT instructions: According to [z80-documented.pdf](https://github.com/floooh/emu-info/blob/master/z80/z80-documented.pdf) the X/Y flags should both be set after the following BIT instruction (because bit 3 and 5 in A are also set):

```
	ld a,0xFF
	bit 1,A
	nop
```
After the BIT instruction, only HF and CF are set, XF and YF are unset (these could also be differences between a Z80 clone and an original Z80?).

**Comment by teeeby** [comment]
IM 1 jumping to 0030 seems to be a bug in Visual Z80 Remix. I don't whether this also happens in Visual Z80 at http://www.visual6502.org/JSSim/expert-z80.html. A real BM1 Z80 clone has been tested and does not have this bug.

I have read your very interesting Z80 articles at The Brain Dump and I sent you an email a couple of days ago. There is a Discord server that discusses the Z80 CPU and emulators in great detail. Please click in the following link to join: https://discord.gg/SsudHPgJ

**Comment by teeeby** [comment]
floooh, please look at the following thread for a way to improve VisualZ80 Remixed:
https://stardot.org.uk/forums/viewtopic.php?p=349760#p349760

**Comment by floooh** [comment]
I'll try to integrate the required changes in the next few days. Many thanks for the thorough investigation and the nudge @teeeby :)

**Comment by redcode** [comment]
Please, take a look at this. The INT request is not aknowledged, and `jr 1` is displayed ad `jr 7`.

![imagen](https://user-images.githubusercontent.com/355282/154700995-6040d2be-c897-4a46-bc44-d0afbe794352.png)
