### ISSUE TITLE
Bad polygon(s) on metal layer (#1) for Z80 sim

### ISSUE THREAD

**Issue by logoliv** [floooh/v6502r#26]
There are some bad polygon points for metal layer (layer #1 in the sim) between #42 and ab0 pins (on the left) and one bad point is completely on the top left of the simulation (near the _busrq pin).
![Capture d’écran 2024-06-11 224243](https://github.com/floooh/v6502r/assets/56048110/39e1e9e2-6c17-4c2e-be88-5d72c27a1daf)
The layer is fine on the http://www.visual6502.org/JSSim/expert-z80.html page and in Z80 Explorer application.

**Comment by floooh** [comment]
Thanks for noticing that and writing the issue. It's most likely a bug in the offline-triangulation script https://github.com/floooh/v6502r/blob/master/ext/visual6502/segdefs.py and only affects rendering, but not the actual emulator functionality.

No promises yet when I get around fixing the issue.

**Comment by logoliv** [comment]
By the way, if I compare your segdefs.c with the original Visual Z80 segdefs.js, it seems all the coordinates have been multiplied by 2 : 
```
var segdefs = [
[ 48,'-',0,4613,4961,4644,4961,4644,4951,4613,4951],
[ 49,'-',0,55,4959,86,4959,86,4949,55,4949],
[ 50,'-',0,4652,4943,4661,4943,4661,4912,4652,4912],
[ 51,'-',0,38,4942,47,4942,47,4911,38,4911]...
```

**Comment by logoliv** [comment]
I noticed that all closed shapes with a "hole" inside are scrambled (like in my capture for the A, 8, 4 and 0 characters, but the V is correct), so my advice is that the problem is in indexation of vertexes for these types of polygons.
![Capture d’écran 2024-06-12 232816](https://github.com/floooh/v6502r/assets/56048110/dcb941a6-e322-4824-a2db-c31e1268b892)

**Comment by fghsgh** [comment]
The original `segdefs.js` file has a weird format for segments that allows defining multiple polygons per segment.

- If there is only one polygon, all the points of the polygon are given in order. The last boundary line is implicit. So something like A,B,C,D to define the polygon ABCD.
- If there are multiple polygons, a duplicate point signifies the end of the polygon, after which a second polygon starts. So something like A,B,C,D,A,E,F,G,H,E to define the polygons ABCD and EFGH (yes, including that final duplicate point).

Note that you cannot simply split these polygons into multiple segments, as one polygon inside another polygon within the same segment should cause it to be inverted, causing a hollow space inside the outer polygon. Meanwhile, a polygon inside another polygon from a _different_ segment will just cause them to overlap.

I figured this out while making my own renderer. I can share my code for reference if requested, but it's written in Lua.

I do not know if all the polygons are still guaranteed to be counterclockwise (I am calculating the signed area of each polygon of each segment and adjusting my polygon rendering accordingly in my code), and I don't know if there are any other formats the segment definition could take on aside from the two above. All my assertion checks succeed though, and I haven't noticed any visual glitches.

**Comment by floooh** [comment]
Thanks a lot for this investigation and detailed explanation @fghsgh! I'm not sure yet when I will return to the project and fix this issue, but a link to your Lua code would be appreciated (fwiw, I didn't spend a lot of time on the offline triangulation, it's all in a sloppily cobbled together python script (https://github.com/floooh/v6502r/blob/master/ext/visual6502/segdefs.py), so when I touch that area again I might as well rewrite the whole renderer and picking code anyway).

**Comment by verhovsky** [comment]
Similar sort of issue in the decode logic part (the top part) of the 6502

<img width="577" alt="Screenshot 2024-12-11 at 10 07 55" src="https://github.com/user-attachments/assets/610950e3-f604-4204-a53d-1b12adf48277" />

**Comment by floooh** [comment]
Some progress by switching to a different triangulation library (https://github.com/joshuaskelly/earcut-python), which is also much faster. I "just" need to figure out how to deal with holes, and some problems that look like in @fghsgh's screenshots.

<img width="203" alt="Screenshot 2024-12-14 at 17 53 45" src="https://github.com/user-attachments/assets/e54c9cf7-1051-49a5-8650-151cb4df4e4f" /><img width="201" alt="Screenshot 2024-12-14 at 17 54 07" src="https://github.com/user-attachments/assets/417ac423-8c80-4594-821a-836951652cfe" /><img width="270" alt="Screenshot 2024-12-14 at 17 54 18" src="https://github.com/user-attachments/assets/b3799ddd-ae2d-4502-82f5-5b8d3b992d10" />

**Comment by floooh** [comment]
I think I got it :)

<img width="194" alt="Screenshot 2024-12-15 at 14 12 02" src="https://github.com/user-attachments/assets/71bd7189-d22f-4940-882f-2b87fd9905a4" />
<img width="215" alt="Screenshot 2024-12-15 at 14 12 11" src="https://github.com/user-attachments/assets/6ba91250-1eeb-426c-9737-35ad2e37d53d" />
<img width="843" alt="Screenshot 2024-12-15 at 14 12 24" src="https://github.com/user-attachments/assets/6d4dbd39-1f99-4524-b703-ea6074204057" />

...with the following triangulation rules:

- on the 6502 segment definition, there are some segments with a duplicate vertex at start, those don't seem to cause any harm, but I'm ignoring those
- for segments with multiple paths (e.g. where a vertex is identical with a start vertex, e.g. the path loops back to the start vertex), all following paths define holes, this situation only exists in the Z80 segment definition
- both the 6502 and 2a03 don't seem to have any 'multi-path segments' (e.g. no segments with holes)

...in the offline triangulation I'm now looking for those special cases and prepare the input to the python earcut library accordingly.

**Comment by floooh** [comment]
PS: the new triangulation doesn't fix those aritfacts in the 6502 simulation though, I think these are actual precision (or maybe rounding) problems in the dataset. For instance on the original visual6502 some of those can be seen too:

<img width="94" alt="image" src="https://github.com/user-attachments/assets/e0c7b067-869f-4f1a-9b68-eea1dd1a6af1" />

> Similar sort of issue in the decode logic part (the top part) of the 6502
> 
> <img alt="Screenshot 2024-12-11 at 10 07 55" width="577" src="https://private-user-images.githubusercontent.com/5687998/394845993-610950e3-f604-4204-a53d-1b12adf48277.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQyNzAxNTUsIm5iZiI6MTczNDI2OTg1NSwicGF0aCI6Ii81Njg3OTk4LzM5NDg0NTk5My02MTA5NTBlMy1mNjA0LTQyMDQtYTUzZC0xYjEyYWRmNDgyNzcucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTIxNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEyMTVUMTMzNzM1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OGZmYWE5YmNhMjIwZWZlZmQ5ZTY1NjFlMmVlZGQwM2Q3MjRjZWE1YWEzMGQ0ZmZmNGFlMzY1MTVjY2Y5MTZlZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.3_vijohcdHla4b4jzb4kIGe_RIsWza_InGjna0KO35Q">
