### ISSUE TITLE
Adding signals to timing diagrams?

### ISSUE THREAD

**Issue by StormTrooper** [floooh/v6502r#4]
I've just started using the visual6502remix and its very useful indeed. Was wonder if phase 2 out can be added to the timing diagrams so I can see exactly what's going on during each instruction?

**Comment by floooh** [comment]
Currently not possible, sorry. The Tracelog window has a "Watch" column, and textfield in the lower right where you can check the status of a single node, but that's not shown in the timing diagram. The information is the same though.

Eventually I'll need to come up with a better UI to watch the status of random nodes both in the tracelog and timing diagram. That single watch node in the tracelog is just the bare minimum.

**Comment by StormTrooper** [comment]
Ok, no problem. Thanks - will use the watch column then.
