### ISSUE TITLE
Antialiasing on high pixel density displays

### ISSUE THREAD

**Issue by verhovsky** [floooh/v6502r#7]
I have a retina (i.e. high pixel density) [monitor](https://www.apple.com/studio-display/specs/) and it seems like v6502r isn't using all the pixels. Compare the anti aliasing on the purple wire with the antialiasing of text in my terminal window:

<img width="255" alt="Screenshot 2023-01-12 at 1 22 07 PM" src="https://user-images.githubusercontent.com/5687998/212173336-466003f8-9e93-4c3d-a273-f9601601f68c.png">

even straight lines are visibly blurry because of the anti aliasing when they could be pixel perfect. Here's a better comparison of an SVG file open in Chrome vs v6502r running locally:

<img width="523" alt="Screenshot 2023-01-12 at 1 37 19 PM" src="https://user-images.githubusercontent.com/5687998/212176088-0e26a07a-36b3-49bd-87fa-df6efa31ae1e.png">

I only changed the Contrast theme to be pure white and compiled it with `./fips build && ./fips run v6502r`. The v6502r window is a bit darker on top because macOS adds a drop shadow under windows.

Looking at https://floooh.github.io/sokol-html5/shadows-sapp.html it seems like this might be a problem with sokol itself.

**Comment by floooh** [comment]
On high-dpi displays rendering happens at half resolution with 4x MSAA to keep pixel fillrate down for lower-end devices.

You can render at full resolution by adding ```.high_dpi = true,``` to the sokol-app initialization block here:

https://github.com/floooh/v6502r/blob/c3bc950c2d15b8682ebc08377881f5361ac6a74a/src/main.c#L168-L185

...on my Mac this yields:

<img width="165" alt="Screenshot 2023-01-13 at 11 55 06" src="https://user-images.githubusercontent.com/1699414/212304177-6d9d0e24-5edb-4fb8-946c-b487e1862fcc.png">

...versus rendering at half resolution with upscaling:

<img width="141" alt="Screenshot 2023-01-13 at 11 59 52" src="https://user-images.githubusercontent.com/1699414/212304801-b34a2313-707c-48be-bfe0-35af965dd8b2.png">

(the differences are easier to spot if you click on the images)

**Comment by floooh** [comment]
FYI: I'm adding a cmdline arg to optionally enable high-dpi, on the native version it would look like this:

```
> v6502r highdpi=true
```

...and on the web it can be activated with an URL arg like this:

https://floooh.github.io/visual6502remix/index.html?highdpi=true

(I'll let you know here when the wasm version has been updated)

**Comment by verhovsky** [comment]
The text is still not high dpi.

**Comment by floooh** [comment]
> The text is still not high dpi.

Yes that's how it is, proper 'high-dpi' text would require embedding different font, and for really high quality text, a different text renderer would need to be integrated, but I'm not going there ;)

The WASM versions have been updated and are available under those URLs:

https://floooh.github.io/visualz80remix/index.html?highdpi=true

https://floooh.github.io/visual6502remix/index.html?highdpi=true

https://floooh.github.io/visual2a03remix/index.html?highdpi=true
